### ISSUE TITLE
Latest update to hack-manager.js not working

### ISSUE THREAD

**Issue by abraxas86** [Jrpl/Bitburner-Scripts#1] opened 2022-02-09 19:09 UTC
Just started in BN2 and couldn't get the hack-manager script to work due to RAM issues.  Noticed the update from @Riley-H-99 today that says it should address this; but the script doesn't seem to run after initiating it.

Running the script:
```
Bitburner v1.4.0 (a3c599e6)
[home ~/]> run hack-manager.js 
Running script with 1 thread(s), pid 19 and args: [].
[home ~/]> ps
[home ~/]> 
```

For the sake of anybody looking at this in the future, this is the copy of the code that I'm running right now:

```
/** @param {NS} ns **/
import { multiscan, gainRootAccess } from "utils.js";

function maxElement(arr) {
	let max = 0;
	for (let i = 0; i < arr.length; i++) {
		if (arr[i] > max) {
			max = arr[i]
		}
	}

	let maxE = arr.indexOf(max);
	return maxE
}

export function best_target(ns, arr) {
	let list = [];
	let results = [];
	arr.forEach(server => {
		if (!ns.hasRootAccess(server)) {
			gainRootAccess(ns, server);
		}

		if (ns.hasRootAccess(server) && ns.getServerRequiredHackingLevel(server) <= ns.getHackingLevel() && server != 'home' && !ns.getPurchasedServers().includes(server)) {
			list.push(server);
		}
	})

	let i = 0;
	list.forEach(target => {
		results[i] = ns.getServerMaxMoney(target);
		i++;
	})

	return list[maxElement(results)];
}

export async function main(ns) {
	while (true) {
		let full_list = multiscan(ns, 'home');

		// finds most profitable server to target
		const hack_target = best_target(ns, full_list);

		// determines threads needed for grow hack and weaken to maintain optimal profit
		const grow_threads = ns.growthAnalyze(hack_target, 2);
		const hack_threads = ns.hackAnalyzeThreads(hack_target, ns.getServerMoneyAvailable(hack_target) / 2);
		const sec_increase = ns.hackAnalyzeSecurity(hack_threads) + ns.growthAnalyzeSecurity(grow_threads);
		let weaken_threads = 1;
		while (ns.weakenAnalyze(weaken_threads) < sec_increase * 1.1) {
			weaken_threads++;
		}

		// determines needed RAM for a cycle of grow weaken hack with determined threads
		const needed_ram = (grow_threads * ns.getScriptRam('targeted-grow.js', 'home') + hack_threads * ns.getScriptRam('targeted-hack.js', 'home') + weaken_threads * ns.getScriptRam('targeted-weaken.js', 'home'));

		// goes through Purchased servers and creates list of servers with enough RAM to utilize 
		// note only Purchased servers are going to reliably have enough RAM
		let purchased_servers = ns.getPurchasedServers();
		let host_servers = [];

		purchased_servers.forEach(server => {
			if (ns.getServerMaxRam(server) >= needed_ram) {
				host_servers.push(server);
			}
		})

		if (ns.getServerMaxRam('home') >= needed_ram) {
			host_servers.push('home');
		}

		if (host_servers == 0) {
			ns.print('Not enough RAM for proper hack cycle current needed is ' + needed_ram);
			return 0
		}

		// prepares target to be hacked uses home to weaken and grow server to required initial conditions
		const initial_growth_amount = .5 * ns.getServerMaxMoney(hack_target) / ns.getServerMoneyAvailable(hack_target);
		let gt = 0;
		if (initial_growth_amount > 1) {
			gt = ns.growthAnalyze(hack_target, initial_growth_amount);
		}

		let wt = 0;
		while (ns.weakenAnalyze(wt) < ns.getServerSecurityLevel(hack_target) + ns.growthAnalyzeSecurity(gt) - ns.getServerMinSecurityLevel(hack_target)) {
			wt++;
		}
		if (wt == 0) {
			wt = 1;
		}

		ns.print(wt + ' ' + gt);

		let prep = 1;
		const prep_RAM = ns.getScriptRam('targeted-grow.js', 'home') * gt + ns.getScriptRam('targeted-weaken.js', 'home') * wt;
		const prep_server = host_servers.find(server => ns.getServerMaxRam(server) - ns.getServerUsedRam(server) >= prep_RAM);
		if (prep_server == null) {
			prep = 0;
		}
		ns.print(prep_server + ' ' + prep);

		if (gt > 1 && prep) {
			ns.exec('targeted-grow.js', prep_server, gt, gt, 0, hack_target);
			ns.exec('targeted-weaken.js', prep_server, wt, wt, hack_target);
			await ns.sleep(ns.getWeakenTime(hack_target) + 1000);
		}

		else if (ns.getServerSecurityLevel(hack_target) > ns.getServerMinSecurityLevel(hack_target) * 1.5 && prep) {
			ns.exec('targeted-weaken.js', prep_server, wt, wt, hack_target);
			await ns.sleep(ns.getWeakenTime(hack_target) + 1000);
		}


		// sets a variable to keep track of time taken executing hacks in the loop
		// if a hack were initiated later than the reset time the first hack would complete changing hack times for every hack following it throwing off the sync
		// most of the time execution time doesn't take that long but this safeguards overly draining a target through desync
		let initial_time = Date.now();
		let k = 0;

		for (let i = 0; i < host_servers.length; i++) {

			let weaken_time = ns.getWeakenTime(hack_target);
			let grow_time = ns.getGrowTime(hack_target);
			let hack_time = ns.getHackTime(hack_target);
			let grow_delay = weaken_time - grow_time - 2;
			let hack_delay = weaken_time - hack_time - 1;

			// assigns a server from the host server list and determines amount of cycles possible
			let server = host_servers[i]
			let n = Math.floor((ns.getServerMaxRam(server) - ns.getServerUsedRam(server)) / needed_ram);

			// writes needed scripts to host server
			await ns.scp('targeted-grow.js', server);
			await ns.scp('targeted-hack.js', server);
			await ns.scp('targeted-weaken.js', server);

			// loops through a cycle of grow weaken and hack executions on the target
			// each script will complete in order of grow hack weaken 2 milliseconds apart
			while (n > 0) {
				if (Date.now() >= initial_time + ns.getHackTime(hack_target)) {
					while (ns.getServerMaxRam(host_servers[k]) - ns.getServerUsedRam(host_servers[k]) < ns.getScriptRam('targeted-weaken', 'home') * weaken_threads) {
						k++;
						if (k == host_servers.length) {
							k = 0;
							await ns.sleep(10000);
						}
					}
					ns.exec('targeted-weaken.js', host_servers[k], weaken_threads, weaken_threads, hack_target);
					await ns.sleep(weaken_time + 20);
					i = 0;
					initial_time = Date.now();
					break
				}

				ns.exec('targeted-weaken.js', server, weaken_threads, weaken_threads, hack_target, n);
				ns.exec('targeted-grow.js', server, grow_threads, grow_threads, grow_delay, hack_target, n);
				ns.exec('targeted-hack.js', server, hack_threads, hack_threads, hack_delay, hack_target, n);
				await ns.sleep(3);

				n--;
			}

			await ns.sleep(5);
		}

		await ns.sleep(10);
	}
}
```

**Comment by Riley-H-99** [comment] 2022-02-09 20:59
Could you copy the end of the log of the script and comment that please? You can access logs of recent scripts by going to active scripts and clicking recent on the top right. I need this to verify that there’s unintended behavior, because the script should end if you don’t have enough available RAM on any of your servers with a message in the log. If that’s not happening the log should contain the runtime error that killed the script.

**Comment by abraxas86** [comment] 2022-02-09 21:21
> Could you copy the end of the log of the script and comment that please? You can access logs of recent scripts by going to active scripts and clicking recent on the top right. I need this to verify that there’s unintended behavior, because the script should end if you don’t have enough available RAM on any of your servers with a message in the log. If that’s not happening the log should contain the runtime error that killed the script.

Oh dang!  I had no idea that section even existed.  I was trying to figure out how I could tail it, but it was closing as fast as it was run.  Thanks for the tip!

My core PC is at 128 GB RAM and 1 core.
The 25 servers that I own were all purchased with the `buy-servers.js` script

Here's the log from the script:

```
getServerRequiredHackingLevel: returned 1 for 'pserv-20'

getHackingLevel: returned 112

getServerRequiredHackingLevel: returned 1 for 'pserv-21'

getHackingLevel: returned 112

getServerRequiredHackingLevel: returned 1 for 'pserv-22'

getHackingLevel: returned 112

getServerRequiredHackingLevel: returned 1 for 'pserv-23'

getHackingLevel: returned 112

getServerRequiredHackingLevel: returned 1 for 'pserv-24'

getHackingLevel: returned 112

getServerMaxMoney: returned $140.000k for 'n00dles'

getServerMaxMoney: returned $4.000m for 'foodnstuff'

getServerMaxMoney: returned $4.600m for 'sigma-cosmetics'

getServerMaxMoney: returned $15.000m for 'zer0'

getServerMaxMoney: returned $0.000 for 'CSEC'

getServerMaxMoney: returned $5.000m for 'joesguns'

getServerMaxMoney: returned $6.000m for 'hong-fang-tea'

getServerMaxMoney: returned $20.000m for 'max-hardware'

getServerMaxMoney: returned $8.000m for 'harakiri-sushi'

getServerMaxMoney: returned $40.000m for 'iron-gym'

getServerMaxMoney: returned $5.500m for 'nectar-net'

getServerMaxMoney: returned $10.000m for 'neo-net'

getServerMoneyAvailable: returned $8.000m for 'iron-gym'

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 32.00GB

getServerMaxRam: returned 128.00GB

Not enough RAM for proper hack cycle current needed is 9275.46737012257

Script finished running
```

**Comment by abraxas86** [comment] 2022-02-09 21:27
I'm gonna be away from my computer for a bit.  I'm sitting just under $100M right now and I'm just gonna farm money through the job ($270.910 / sec) and hacknet ($6.069k / sec).  I was thinking about re-running the servers script to get better servers but I'll hold tight and follow your direction in case you want me to test anything.

**Comment by Riley-H-99** [comment] 2022-02-10 08:21
At this point it seems everything is working as intended. I'm working on an update that should work when you have less RAM available earlier in a bit node run. I'm going to close this issue but one last thing to note is the number for needed RAM will go down with augments and higher hacking levels.

**Closed as completed by Riley-H-99** 2022-02-10 08:21 UTC

**Comment by abraxas86** [comment] 2022-02-10 14:15
Sounds good.  Thanks for following up, and sorry for the non-issue report.
